# Faça um programa que leia um numero inteiro qualquer e mostre na tela a sua tabuada.

n = int(input('Digite um número para ver a tabuada: '))
print('A tabuada de {}'.format(n))
print('-' * 14)
print('{} x 1 = {}'.format(n, n * 1))
print('{} x 2 = {}'.format(n, n * 2))
print('{} x 3 = {}'.format(n, n * 3))
print('{} x 4 = {}'.format(n, n * 4))
print('{} x 5 = {}'.format(n, n * 5))
print('{} x 6 = {}'.format(n, n * 6))
print('{} x 7 = {}'.format(n, n * 7))
print('{} x 8 = {}'.format(n, n * 8))
print('{} x 9 = {}'.format(n, n * 9))
print('{} x 10 = {}'.format(n, n * 10))
print('-' * 14)
# podendo tambem fazer dessa forma abaixo!

n = int(input('Digite um número para ver a tabuada: '))
print('-' * 14)
print('{} x {:2} = {}'.format(n, 1, n*1))
print('{} x {:2} = {}'.format(n, 2, n*2))
print('{} x {:2} = {}'.format(n, 3, n*3))
print('{} x {:2} = {}'.format(n, 4, n*4))
print('{} x {:2} = {}'.format(n, 5, n*5))
print('{} x {:2} = {}'.format(n, 6, n*6))
print('{} x {:2} = {}'.format(n, 7, n*7))
print('{} x {:2} = {}'.format(n, 8, n*8))
print('{} x {:2} = {}'.format(n, 9, n*9))
print('{} x {:2} = {}'.format(n, 10, n*10))
print('-' * 14)
